version: "3.7"

services:
  swarm_watch:
    image: afrianjunior/swarm-watch
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
